# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Runif <- function(n, min = 0, max = 1) {
    .Call(`_rangen_runif`, n, min, max)
}

Rbeta <- function(n, alpha, beta) {
    .Call(`_rangen_rbeta`, n, alpha, beta)
}

Rexp <- function(n, rate = 1) {
    .Call(`_rangen_rexp`, n, rate)
}

Rchisq <- function(n, df) {
    .Call(`_rangen_rchisq`, n, df)
}

Rgamma <- function(n, shape, rate = 1) {
    .Call(`_rangen_rgamma`, n, shape, rate)
}

Rgeom <- function(n, prob) {
    .Call(`_rangen_rgeom`, n, prob)
}

Rcauchy <- function(n, location = 0, scale = 1) {
    .Call(`_rangen_rcauchy`, n, location, scale)
}

Rt <- function(n, df, ncp) {
    .Call(`_rangen_rt`, n, df, ncp)
}

Rpareto <- function(n, shape = 1, scale = 1) {
    .Call(`_rangen_rpareto`, n, shape, scale)
}

Rfrechet <- function(n, lambda = 1, mu = 0, sigma = 1) {
    .Call(`_rangen_rfrechet`, n, lambda, mu, sigma)
}

Rlaplace <- function(n, mu = 0, sigma = 1) {
    .Call(`_rangen_rlaplace`, n, mu, sigma)
}

Rgumblet <- function(n, mu = 0, sigma = 1) {
    .Call(`_rangen_rgumble`, n, mu, sigma)
}

Rarcsine <- function(n, min = 0, max = 1) {
    .Call(`_rangen_rarcsine`, n, min, max)
}

Sample.int <- function(n, size = n, replace = FALSE, seed = nanoTime()) {
    .Call(`_rangen_sample_int`, n, size, replace, seed)
}

Sample <- function(x, size = length(x), replace = FALSE, seed = nanoTime()) {
    .Call(`_rangen_sample`, x, size, replace, seed)
}

colSample <- function(x, size = rep_len(nrow(x), ncol(x)), replace = rep_len(FALSE, ncol(x)), parallel = FALSE, cores = 0, seed = nanoTime()) {
    .Call(`_rangen_colSample`, x, size, replace, parallel, cores, seed)
}

rowSample <- function(x, size = rep_len(ncol(x), nrow(x)), replace = rep_len(FALSE, nrow(x)), parallel = FALSE, cores = 0, seed = nanoTime()) {
    .Call(`_rangen_rowSample`, x, size, replace, parallel, cores, seed)
}

nanoTime <- function() {
    .Call(`_rangen_nanoTime`)
}

