# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Runif <- function(n, min = 0.0, max = 1.0) {
    .Call(`_rangen_runif`, n, min, max)
}

Rbeta <- function(n, alpha, beta) {
    .Call(`_rangen_rbeta`, n, alpha, beta)
}

Rexp <- function(n, rate = 1) {
    .Call(`_rangen_rexp`, n, rate)
}

Rchisq <- function(n, df) {
    .Call(`_rangen_rchisq`, n, df)
}

Rgamma <- function(n, shape, rate = 1) {
    .Call(`_rangen_rgamma`, n, shape, rate)
}

Rgeom <- function(n, prob) {
    .Call(`_rangen_rgeom`, n, prob)
}

Rcauchy <- function(n, location = 0, scale = 1) {
    .Call(`_rangen_rcauchy`, n, location, scale)
}

Rt <- function(n, df, ncp) {
    .Call(`_rangen_rt`, n, df, ncp)
}

Rpareto <- function(n, shape = 1, scale = 1) {
    .Call(`_rangen_rpareto`, n, shape, scale)
}

Rfrechet <- function(n, lambda = 1, mu = 0, sigma = 1) {
    .Call(`_rangen_rfrechet`, n, lambda, mu, sigma)
}

Rlaplace <- function(n, mu = 0, sigma = 1) {
    .Call(`_rangen_rlaplace`, n, mu, sigma)
}

Rgumble <- function(n, mu = 0, sigma = 1) {
    .Call(`_rangen_rgumble`, n, mu, sigma)
}

Rarcsine <- function(n, min = 0, max = 1) {
    .Call(`_rangen_rarcsine`, n, min, max)
}

Rnorm <- function(n) {
    .Call(`_rangen_rnorm`, n)
}

colRunif <- function(nrow, ncol, min = rep_len(0, ncol), max = rep_len(1, ncol)) {
    .Call(`_rangen_colRunif`, nrow, ncol, min, max)
}

colRbeta <- function(nrow, ncol, alpha, beta) {
    .Call(`_rangen_colRbeta`, nrow, ncol, alpha, beta)
}

colRexp <- function(nrow, ncol, rate = rep_len(1, ncol)) {
    .Call(`_rangen_colRexp`, nrow, ncol, rate)
}

colRchisq <- function(nrow, ncol, df) {
    .Call(`_rangen_colRchisq`, nrow, ncol, df)
}

colRgamma <- function(nrow, ncol, shape, rate = rep_len(1, ncol)) {
    .Call(`_rangen_colRgamma`, nrow, ncol, shape, rate)
}

colRgeom <- function(nrow, ncol, prob) {
    .Call(`_rangen_colRgeom`, nrow, ncol, prob)
}

colRcauchy <- function(nrow, ncol, location = rep_len(0, ncol), scale = rep_len(1, ncol)) {
    .Call(`_rangen_colRcauchy`, nrow, ncol, location, scale)
}

colRt <- function(nrow, ncol, df, ncp) {
    .Call(`_rangen_colRt`, nrow, ncol, df, ncp)
}

colRpareto <- function(nrow, ncol, shape = rep_len(1, ncol), scale = rep_len(1, ncol)) {
    .Call(`_rangen_colRpareto`, nrow, ncol, shape, scale)
}

colRfrechet <- function(nrow, ncol, lambda = rep_len(1, ncol), mu = rep_len(0, ncol), sigma = rep_len(1, ncol)) {
    .Call(`_rangen_colRfrechet`, nrow, ncol, lambda, mu, sigma)
}

colRlaplace <- function(nrow, ncol, mu = rep_len(0, ncol), sigma = rep_len(1, ncol)) {
    .Call(`_rangen_colRlaplace`, nrow, ncol, mu, sigma)
}

colRgumble <- function(nrow, ncol, mu = rep_len(0, ncol), sigma = rep_len(1, ncol)) {
    .Call(`_rangen_colRgumble`, nrow, ncol, mu, sigma)
}

colRarcsine <- function(nrow, ncol, min = rep_len(0, ncol), max = rep_len(1, ncol)) {
    .Call(`_rangen_colRarcsine`, nrow, ncol, min, max)
}

colRnorm <- function(nrow, ncol) {
    .Call(`_rangen_colRnorm`, nrow, ncol)
}

Runif.mat <- function(nrow, ncol, min = 0, max = 1) {
    .Call(`_rangen_runif_mat`, nrow, ncol, min, max)
}

Rbeta.mat <- function(nrow, ncol, alpha, beta) {
    .Call(`_rangen_rbeta_mat`, nrow, ncol, alpha, beta)
}

Rexp.mat <- function(nrow, ncol, rate = 1) {
    .Call(`_rangen_rexp_mat`, nrow, ncol, rate)
}

Rchisq.mat <- function(nrow, ncol, df) {
    .Call(`_rangen_rchisq_mat`, nrow, ncol, df)
}

Rgamma.mat <- function(nrow, ncol, shape, rate = 1) {
    .Call(`_rangen_rgamma_mat`, nrow, ncol, shape, rate)
}

Rgeom.mat <- function(nrow, ncol, prob) {
    .Call(`_rangen_rgeom_mat`, nrow, ncol, prob)
}

Rcauchy.mat <- function(nrow, ncol, location = 0, scale = 1) {
    .Call(`_rangen_rcauchy_mat`, nrow, ncol, location, scale)
}

Rt.mat <- function(nrow, ncol, df, ncp) {
    .Call(`_rangen_rt_mat`, nrow, ncol, df, ncp)
}

Rpareto.mat <- function(nrow, ncol, shape = 1, scale = 1) {
    .Call(`_rangen_rpareto_mat`, nrow, ncol, shape, scale)
}

Rfrechet.mat <- function(nrow, ncol, lambda = 1, mu = 0, sigma = 1) {
    .Call(`_rangen_rfrechet_mat`, nrow, ncol, lambda, mu, sigma)
}

Rlaplace.mat <- function(nrow, ncol, mu = 0, sigma = 1) {
    .Call(`_rangen_rlaplace_mat`, nrow, ncol, mu, sigma)
}

Rgumble.mat <- function(nrow, ncol, mu = 0, sigma = 1) {
    .Call(`_rangen_rgumble_mat`, nrow, ncol, mu, sigma)
}

Rarcsine.mat <- function(nrow, ncol, min = 0, max = 1) {
    .Call(`_rangen_rarcsine_mat`, nrow, ncol, min, max)
}

Rnorm.mat <- function(nrow, ncol) {
    .Call(`_rangen_rnorm_mat`, nrow, ncol)
}

Sample.int <- function(n, size = n, replace = FALSE) {
    .Call(`_rangen_sample_int`, n, size, replace)
}

Sample <- function(x, size = length(x), replace = FALSE) {
    .Call(`_rangen_sample`, x, size, replace)
}

colSample <- function(x, size = rep_len(nrow(x), ncol(x)), replace = rep_len(FALSE, ncol(x)), parallel = FALSE, cores = 0) {
    .Call(`_rangen_colSample`, x, size, replace, parallel, cores)
}

rowSample <- function(x, size = rep_len(ncol(x), nrow(x)), replace = rep_len(FALSE, nrow(x)), parallel = FALSE, cores = 0) {
    .Call(`_rangen_rowSample`, x, size, replace, parallel, cores)
}

nanoTime <- function() {
    .Call(`_rangen_nanoTime`)
}

set_seed <- function(seed = nanoTime()) {
    invisible(.Call(`_rangen_set_seed`, seed))
}

